line_tracker:
  ros__parameters:
    img_width: 640
    img_height: 480

    x_min: 211
    x_max: 429
    y_min: 240
    y_max: 480

    low_h: 0
    high_h: 50
    low_s: 0
    high_s: 45
    low_v: 0
    high_v: 45